language: java
jdk:
  - oraclejdk8

sudo: required

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get install --assume-yes --option Dpkg::Options::="--force-confnew" docker-engine
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/1.7.1/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo cp docker-compose /usr/local/bin && rm docker-compose

install: true

before_script:
  - docker --version
  - docker-compose --version
  - docker-compose up -d

script:
  - mvn clean
  - mvn verify -P code-quality,documentation,release -DskipITs
  - mvn integration-test -Dtest.targetBrowser=firefox
  - mvn integration-test -Dtest.targetBrowser=chrome

after_success:
  - bash <(curl -s https://codecov.io/bash)

addons:
  apt:
    packages:
      - oracle-java8-installer
