#
# Selenium Grid with Firefox and Chrome nodes for development and testing
#
version: '2'

services:
  hub:
    image: selenium/hub:$SELENIUM_IMAGE_VERSION
    ports:
      - "4444:4444"
  firefox:
    image: selenium/node-firefox:$SELENIUM_IMAGE_VERSION
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
  chrome:
    image: selenium/node-chrome:$SELENIUM_IMAGE_VERSION
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub

